### ISSUE TITLE
Retry delay

### ISSUE THREAD

**Issue by daviskirk** [nameko/nameko-sqlalchemy#22]
Would it make sense to add an optional delay or backoff to the retry decorator?  
Or would the recommendation be to use https://github.com/nameko/nameko-amqp-retry in this case?

**Comment by mattbennett** [comment]
I think in most cases that immediately retrying would be sufficient. If the database has really gone down I'd probably prefer my application to throw an error than to wait for it to come back.

We haven't actually used this yet though, so I could be persuaded otherwise.

**Comment by daviskirk** [comment]
@mattbennett I was initially convinced by your answer (thanks), however we have run into problems with this.  For long-running entrypoints and flaky database connections we often get the situation where the database goes down for a few seconds (but long enough for the retry to fail) and retrying the whole entrypoint (amqp-retry) takes up a lot of resources.  The current decorator only helps if the there's a direct reconnect.  
I'd be happy to contribute a pull request, but given that you aren't using this (and it might not apply for stable database connections) I ok if this is not something you'd want to have in the package.

**Comment by mattbennett** [comment]
@daviskirk I think it's OK to add this, as long as the default remains sensible. Retry decorators very often have delay and backoff parameters, I don't see why this one shouldn't. Would welcome a PR :)
